# Generated by Django 3.0.7 on 2020-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20200630_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['term']},
        ),
        migrations.AlterField(
            model_name='word',
            name='term',
            field=models.CharField(max_length=100, unique=True, verbose_name='palabra'),
        ),
    ]
