# Generated by Django 3.0.7 on 2020-07-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20200701_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['term'], 'verbose_name': 'término'},
        ),
    ]
